Target Android 14
shadowsocks/shadowsocks-android pull request #3165
Opened 2024-08-26 09:24 UTC by AaronChen0

This is an attempt to update shadowsocks-android to target Android 14 and its dependencies.

Please read [this](https://developer.android.com/build/releases/past-releases/agp-8-0-0-release-notes#default-changes) for changes in AGP8. Some build option default values change.

The build succeeded and the debug apk works in both my android 14 and android 12 phones.

2024-08-26 15:57 UTC, AaronChen0 commented
In a release branch [here](https://github.com/AaronChen0/shadowsocks-android/tree/android14_release), the build will fail with the following R8 missing class errors:
```
WARNING: /home/circleci/code/mobile/build/intermediates/merged_java_res/release/mergeReleaseJavaResource/base.jar: R8: Unexpected reference to missing service class: META-INF/services/java.net.spi.InetAddressResolverProvider.
WARNING: /home/circleci/code/mobile/build/intermediates/merged_java_res/release/mergeReleaseJavaResource/base.jar: R8: Unexpected reference to missing service implementation class in META-INF/services/java.net.spi.InetAddressResolverProvider: org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider.
WARNING: /home/circleci/code/mobile/build/intermediates/merged_java_res/release/mergeReleaseJavaResource/base.jar: R8: Unexpected reference to missing service class: META-INF/services/sun.net.spi.nameservice.NameServiceDescriptor.
ERROR: Missing classes detected while running R8. Please add the missing classes or apply additional keep rules that are generated in /home/circleci/code/mobile/build/outputs/mapping/release/missing_rules.txt.
ERROR: R8: Missing class lombok.Generated (referenced from: org.slf4j.Logger org.xbill.DNS.Compression.log and 3 other contexts)
Missing class org.slf4j.impl.StaticLoggerBinder (referenced from: void org.slf4j.LoggerFactory.bind() and 3 other contexts)
Missing class org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider (referenced from: java.util.List kotlinx.coroutines.internal.FastServiceLoader.load(java.lang.Class, java.lang.ClassLoader))
Missing class sun.net.spi.nameservice.NameServiceDescriptor (referenced from: org.xbill.DNS.spi.DNSJavaNameServiceDescriptor)
```
Adding the following to `proguard-rules.pro` fixes the R8 errors and the apk works normally.
```
-dontwarn java.net.spi.InetAddressResolverProvider
-dontwarn org.slf4j.impl.StaticLoggerBinder
-dontwarn org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider
-dontwarn sun.net.spi.nameservice.NameServiceDescriptor
-dontwarn lombok.Generated
```
I am not familiar with R8 proguard rules, should I just add `dontwarn` if the app works normally in my use?
Check the builds [here](https://app.circleci.com/pipelines/circleci/YBg2SAd5kz9ouc3TKNZvz3/KRnxuTDpRx85DnYaX86Nc6?branch=android14_release).

2024-08-26 17:00 UTC, Mygod commented
Yes add these rules.

```
-dontwarn lombok.Generated
-dontwarn org.slf4j.impl.StaticLoggerBinder
-dontwarn org.xbill.DNS.spi.DnsjavaInetAddressResolverProvider
-dontwarn sun.net.spi.nameservice.NameServiceDescriptor
```

2024-08-26 18:19 UTC, Mygod requested changes

2024-08-26 18:19 UTC, Mygod commented on core/src/main/AndroidManifest.xml
> +                android:value="Vpn" />
https://developer.android.com/about/versions/14/changes/fgs-types-required#system-exempted

2024-08-26 18:19 UTC, Mygod commented on mobile/src/main/AndroidManifest.xml
> +                android:value="tile" />
This is not necessary.

2024-08-27 03:02 UTC, AaronChen0 commented
Build successfully and work in my phones. Please review.

2024-08-27 05:17 UTC, Mygod commented
Thanks! And be patient while I download rust. :)

2024-08-28 08:00 UTC, Mygod approved these changes
LGTM

2024-08-28 16:20 UTC, merged